AWSTemplateFormatVersion: 2010-09-09 
Description: >- 
  This template will provision a launch template for the Web server Environment (Windows IIS).  
  v0.1 
 
Metadata: 
  'AWS::CloudFormation::Interface': 
    ParameterGroups: 
      - # Basic Configuration 
        Label: 
          default: Basic Configuration 
        Parameters: 
          - Environment 
      - # Launch Template Configuration 
        Label: 
          default: Launch Template Configuration 
        Parameters: 
          - InstanceType 
          - Monitoring 
          - ExpWebLtSgr 
    ParameterLabels: 
      Environment: 
        default: Environment Label 
      Monitoring: 
        default: Monitoring 
      ExpWebLtSgr: 
        default: Exp Web Launch Template Security Group 
 
Parameters: 
  Environment: 
    Description: Enter an envrionment label to assign this template. 
    Type: String 
  InstanceType: 
    AllowedValues: 
      - "t2.large" 
      - "t3.large" 
      - "m5a.large" 
    Default: "t3.large" 
    Description: Select the Ec2 Instance Type for this launch template. 
    Type: String 
  Monitoring: 
    AllowedValues: 
      - "Yes" 
      - "No" 
    Default: "No" 
    Description: Select to enable monitoring for the launch template. 
    Type: String 
  ExpWebLtSgr: 
    Description: Select one or more security groups for the Exp Launch Template. 
    Type: List<AWS::EC2::SecurityGroup::Id> 
 
Conditions: 
  Monitor: 
    !Equals [!Ref Monitoring, "Yes"] 
 
Resources: 
# EC2 Launch Template 
  ExpWebLT: 
    Type: AWS::EC2::LaunchTemplate 
    Metadata: 
      'AWS::CloudFormation::Authentication': 
        S3AccessCreds: 
          type: S3 
          roleName: !Ref ExpwebRole 
          buckets: 
            - '{{resolve:ssm:scripts-bucket:1}}' 
      "AWS::CloudFormation::Init": 
        configSets: 
          configuration: 
            - init 
            - InitialSetup 
            - InstallIIS 
            - CreateHealthCheck 
            - JoinAD 
        init: # Initialize cfn 
          files: 
            'C:\cfn\scripts\SetupDefaults.json': 
              content: !Sub 
                - | 
                  { 
                    "StackName": "${AWS::StackName}", 
                    "Region": "${AWS::Region}", 
                    "Resource": "ExpWebLT", 
                    "directoryName": "${AccountShortName}.com", 
                    "Joiner": "${AccountShortName}/ad/joiner" 
                  } 
                - AccountShortName: '{{resolve:ssm:AccountShortName:1}}' 
          commands: 
            SetExecutionPolicy: 
              command: >- 
                powershell.exe -Command "Set-ExecutionPolicy RemoteSigned -Force" 
              waitAfterCompletion: 0 
          services: 
            windows: 
              cfn-hup: 
                enabled: True 
                ensureRunning: True 
                files: 
                  - C:\cfn\cfn-hup.conf 
        InitialSetup: # Initial Setup 
          files: 
            'C:\cfn\scripts\Initial-Setup.ps1': 
              source: !Join 
                - '' 
                - - 'https://s3-us-west-2.amazonaws.com/' 
                  - '{{resolve:ssm:scripts-bucket:1}}' 
                  - '/Exp_web/Initial-Setup.ps1' 
              authentication: S3AccessCreds 
          commands: 
            InitialSetup: 
              command: >- 
                powershell.exe -Command "C:\cfn\scripts\Initial-Setup.ps1" 
              waitAfterCompletion: 0 
        InstallIIS: # Install IIS components 
          files: 
            'C:\cfn\scripts\Install-IIS.ps1': 
              source: !Join 
                - '' 
                - - 'https://s3-us-west-2.amazonaws.com/' 
                  - '{{resolve:ssm:scripts-bucket:1}}' 
                  - '/Exp_web/Install-IIS.ps1' 
              authentication: S3AccessCreds 
          commands: 
            InstallIIS: 
              command: >- 
                powershell.exe -Command "C:\cfn\scripts\Install-IIS.ps1" 
              waitAfterCompletion: 0 
        CreateHealthCheck: # Create Health Check site 
          files: 
            'C:\cfn\scripts\Create-HealthCheckSite.ps1': 
              source: !Join 
                - '' 
                - - 'https://s3-us-west-2.amazonaws.com/' 
                  - '{{resolve:ssm:scripts-bucket:1}}' 
                  - '/Exp_web/Create-HealthCheckSite.ps1' 
              authentication: S3AccessCreds 
            'D:\webroot\healthcheck\index.htm': 
              source: !Join 
                - '' 
                - - 'https://s3-us-west-2.amazonaws.com/' 
                  - '{{resolve:ssm:scripts-bucket:1}}' 
                  - '/Exp_web/index.htm' 
              authentication: S3AccessCreds 
          commands: 
            CreateHealthCheck: 
              command: >- 
                powershell.exe -Command "C:\cfn\scripts\Create-HealthCheckSite.ps1" 
              waitAfterCompletion: 0 
        JoinAD: # Join Active Directory 
          files: 
            'C:\cfn\scripts\Join-AD.ps1': 
              source: !Join 
                - '' 
                - - 'https://s3-us-west-2.amazonaws.com/' 
                  - '{{resolve:ssm:scripts-bucket:1}}' 
                  - '/Exp_web/Join-AD.ps1' 
              authentication: S3AccessCreds 
          commands: 
            JoinAD: 
              command: >- 
                powershell.exe -Command "C:\cfn\scripts\Join-AD.ps1" 
              waitAfterCompletion: forever 
    Properties: 
      LaunchTemplateName: !Sub "${Environment}-Exp-web-lt" 
      LaunchTemplateData: 
        BlockDeviceMappings: 
          - DeviceName: xvdf 
            Ebs: 
              DeleteOnTermination: true 
              Encrypted: true 
              VolumeSize: 10 
              VolumeType: gp2 
        IamInstanceProfile: 
          Name: !Ref ExpwebProfile 
        ImageId: '{{resolve:ssm:ImageId:1}}' 
        InstanceType: !Ref InstanceType 
        KeyName: !Join ['',['kp-','{{resolve:ssm:AccountShortName:1}}','-default']] 
        Monitoring: 
          Enabled: !If [Monitor, True, False] 
        SecurityGroupIds: !Ref ExpWebLtSgr 
        TagSpecifications: 
          - 
            ResourceType: instance 
            Tags: 
              - 
                Key: Name 
                Value: !Sub "${Environment}-Exp-web" 
              - 
                Key: Environment 
                Value: !Ref Environment 
        UserData: 
          Fn::Base64: 
            Fn::Sub: 
              | 
              <script> 
              cfn-init.exe -v -s ${AWS::StackName} -r ExpWebLT -c configuration --region ${AWS::Region} 
              </script> 
 
# IAM 
  ExpwebPolicy: 
    Type: AWS::IAM::ManagedPolicy 
    Properties:  
      ManagedPolicyName: example-web-policy 
      PolicyDocument:  
        Version: "2012-10-17" 
        Statement:  
          - # Secrets Manager 
            Sid: "SecretsManager" 
            Effect: "Allow" 
            Action: 
              - "secretsmanager:GetSecretValue" 
            Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:*/ad/joiner*" 
          - # CloudFormation 
            Sid: CloudFormation1 
            Effect: Allow 
            Action: 
              - cloudformation:SignalResource* 
            Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}/*" 
          - # S3 
            Sid: "S3" 
            Effect: "Allow" 
            Action: 
              - "s3:GetObject" 
            Resource: !Join 
              - '' 
              - - 'arn:aws:s3:::' 
                - '{{resolve:ssm:scripts-bucket:1}}' 
                - '/Exp_web/*' 
  ExpwebRole: 
    Type: AWS::IAM::Role 
    Properties:  
      AssumeRolePolicyDocument: 
        Version: "2012-10-17" 
        Statement:  
          -  
            Effect: Allow 
            Principal:  
              Service:  
                - ec2.amazonaws.com 
            Action:  
              - sts:AssumeRole 
      ManagedPolicyArns: 
        - !Ref ExpwebPolicy 
      Path: "/" 
      RoleName: !Sub "example-default-${AWS::Region}" 
  ExpwebProfile:  
    Type: AWS::IAM::InstanceProfile 
    Properties:  
      Path: "/" 
      Roles:  
        -  
          !Ref ExpwebRole 
      InstanceProfileName: !Sub "example-default-profile-${AWS::Region}" 
 