AWSTemplateFormatVersion: 2010-09-09
Description: Template to create Windows Server Patching Maintenace Window, Targets and Tasks. Use Default Values for quick completion - Add your own values for customization.

Metadata:
  License: Apache-2.0
  Author: Dennis Christilaw
  URL: https://github.com/Talderon/AWS_CloudFormation
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Maintenance Window Configuration"
        Parameters:
          - MaintenanceWindowName
          - MaintenanceWindowDescription
          - MaintenanceWindowSchedule
          - MaintenanceWindowDuration
          - MaintenanceWindowCutoff
          - MainteanceWindowTimezone
      -
        Label:
          default: "Maintenance Target Configuration"
        Parameters:
          - MaintenanceTargetName
          - MaintenanceTargetDescription
          - MaintenanceTargetTarget
          - MaintenaneTargetKeyValue
      -
        Label:
          default: "Maintenance Target Run Command Configuration"
        Parameters:
          - MaintenanceWindowRunCommandTaskName
          - MaintenanceWindowRunCommandTaskPriority
          - MaintenanceWindowRunCommandTaskMaxConcurrency
          - MaintenanceWindowRunCommandTaskMaxErrors
          - MaintenanceTargetSNSARN
          - MaintenanceRunCommandS3Bucket
          - MaintenanceRunCommandS3BucketPrefix
    ParameterLabels:
      MaintenanceWindowName:
        default: "Maintenance Window Name (lowecase, no spaces)"
      MaintenanceWindowDescription:
        default: "Maintenance Window Description (128 char max)"
      MainteanceWindowTimezone:
        default: "Timezone format as found here: https://docs.aws.amazon.com/redshift/latest/dg/time-zone-names.html"
      MaintenanceWindowDuration:
        default: "Maintenance Window Duration (in hours)"
      MaintenanceWindowCutoff:
        default: "Maintenance Window Cutoff (in hours before window closes)"
      MaintenanceWindowSchedule:
        default: "Maintenance Window Schedule"
      MaintenanceTargetName:
        default: "Maintenance Target Config Name (lowercase, no spaces)"
      MaintenanceTargetDescription:
        default: "Maintenance Target Config Description (128 char max)"
      MaintenanceTargetTarget:
        default: "Maintenance Target Tag Key (format: tag:{keyName})"
      MaintenaneTargetKeyValue:
        default: "Maintenance Target Key Value"
      MaintenanceWindowRunCommandTaskName:
        default: "Run Command Name (lowercase, no spaces)"
      MaintenanceWindowRunCommandTaskPriority:
        default: "Run Command Task Priority"      
      MaintenanceWindowRunCommandTaskMaxConcurrency:
        default: "Run Command Max Concurrency"
      MaintenanceWindowRunCommandTaskMaxErrors:
        default: "Run Command Max Error Rate" 
      MaintenanceTargetSNSARN:
        default: "ARN of the SNS Topic to send notifications through"
      MaintenanceRunCommandS3Bucket:
        default: S3 Bucket Name to store logs
      MaintenanceRunCommandS3BucketPrefix:
        default: S3 Bucket prefix to assign logs for this job

Parameters:
  MaintenanceWindowName:
    Description: Maintenace Window Name
    Type: String
  MaintenanceWindowDescription:
    Description: Sample - Second THU of the month Windows Server Patching
    Type: String
    MaxLength: '128'
  MainteanceWindowTimezone:
    Description: Timezone for schedule (AWS will convert to UTC) (Optional, can be removed, WIll default to UTC)
    Type: String
    Default: US/Pacific
  MaintenanceWindowDuration:
    Description: How many hours the maintenance window will run from start Timezone (1-4 hrs)
    Type: Number
    Default: 3
    MinValue: 1
    MaxValue: 4
  MaintenanceWindowCutoff:
    Description: How many hours before maintenance window end will new jobs not start (1-2 hrs) (Optional, can be removed)
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 2
  MaintenanceWindowSchedule:
    Description: Cron/Rate expression for schedule - Sample - cron(0 0 20 ? 1/1 5#2 *)
    Type: String
    Default: cron(0 0 20 ? 1/1 5#2 *)
  MaintenanceTargetName:
    Description: Maintenace Target Name (No Spaces)
    Type: String
  MaintenanceTargetDescription:
    Description: Sample - UAT Server Patching
    Type: String
    MaxLength: '128'
  MaintenanceTargetTarget:
    Description: Tag Key should equal 'Patch Group'
    Type: String
    Default: tag:Patch Group
  MaintenaneTargetKeyValue:
    Description: Tag Value for Patch Group - Example -  UAT-Group-01-THU-Patches
    Type: String
    Default: UAT-Group-01-THU-Patches
  MaintenanceWindowRunCommandTaskName:
    Description: Maintenace Window Task Name (No Spaces)
    Type: String
  MaintenanceWindowRunCommandTaskPriority:
    Description: Job Priority - Number 0 - 5
    Type: Number
    Default: 1
    MinValue: 0
    MaxValue: 5
  MaintenanceWindowRunCommandTaskMaxConcurrency:
    Description: Integer or Percentage
    Type: String
    Default: 50%
    AllowedPattern: ^([1-9][0-9]*|[1-9][0-9]%|[1-9]%|100%)$
  MaintenanceWindowRunCommandTaskMaxErrors:
    Description: Integer or Percentage
    Type: String
    Default: 25%
    AllowedPattern: ^([1-9][0-9]*|[1-9][0-9]%|[1-9]%|100%)$
  MaintenanceTargetSNSARN:
    Description: ARN of the SNS Topic to send notifications through
    Type: String
  MaintenanceRunCommandS3Bucket:
    Description: S3 Bucket Name (not ARN) where you want to store logs
    Type: String
  MaintenanceRunCommandS3BucketPrefix:
    Description: S3 Sub-Bucket Name (not ARN) where you want to store logs
    Type: String

Resources:
  MaintenanceWindow:
    Type: 'AWS::SSM::MaintenanceWindow'
    Properties:
      AllowUnassociatedTargets: false
      Cutoff: !Ref MaintenanceWindowCutoff
      Description: !Ref MaintenanceWindowDescription
      Duration: !Ref MaintenanceWindowDuration
      Name: !Ref MaintenanceWindowName
      Schedule: !Ref MaintenanceWindowSchedule
      ScheduleTimezone: !Ref MainteanceWindowTimezone
  MaintenanceWindowTarget:
    Type: 'AWS::SSM::MaintenanceWindowTarget'
    Properties:
      Name: !Ref MaintenanceTargetName
      Description: !Ref MaintenanceTargetDescription
      WindowId: !Ref MaintenanceWindow
      ResourceType: 'INSTANCE'
      Targets:
        - Key: !Ref MaintenanceTargetTarget
          Values: 
          - !Ref MaintenaneTargetKeyValue
  MaintenanceWindowRunCommandTask:
    Type: 'AWS::SSM::MaintenanceWindowTask'
    Properties:
      WindowId: !Ref MaintenanceWindow
      Targets:
        - Key: WindowTargetIds
          Values:
            - !Ref MaintenanceWindowTarget
      TaskArn: AWS-RunPatchBaseline
      TaskType: RUN_COMMAND
      TaskInvocationParameters:
        MaintenanceWindowRunCommandParameters: # This value tends to not change from Account to Account unless it is updated by AWS. You can verify it here: AWS Systems Manager/Documents/Document Name: AWS-RunPatchBaseline
          DocumentHash: 945ae15356b0f6ba7bce2a738101b8822cedef3bf5c027abc3bb9023aaec8b1b
          DocumentHashType: Sha256
          NotificationConfig:
            NotificationArn: !Ref MaintenanceTargetSNSARN
            NotificationEvents: 
              - All
            NotificationType: Command
          OutputS3BucketName: !Ref MaintenanceRunCommandS3Bucket
          OutputS3KeyPrefix: !Ref MaintenanceRunCommandS3BucketPrefix
      Priority: !Ref MaintenanceWindowRunCommandTaskPriority
      MaxConcurrency: !Ref MaintenanceWindowRunCommandTaskMaxConcurrency
      MaxErrors: !Ref MaintenanceWindowRunCommandTaskMaxErrors
      Name: !Ref MaintenanceWindowRunCommandTaskName
